### ISSUE TITLE
Amari 2.2.2.0 and HDP 2.4 upgrade

### ISSUE THREAD

**Issue by ygy** [brooklyncentral/brooklyn-ambari#116]
HDP 2.4 comes with Ambari 2.2.2.0 which requires all configuration options to be attached to services.

If BP contains config similar to the one bellow

```
    ambariConfigMap:
      hdfs-site:
        dfs.webhdfs.enabled: true
        dfs.permissions.enabled: false
      httpfs-site:
        httpfs.proxyuser.hue: '*'
        httpfs.proxyuser.hue.groups: '*'
```
Ambari returns the following error
```
Caused by: io.brooklyn.ambari.rest.AmbariApiException: Error from the Ambari REST API - HTTP/400 [http://ec2-52-198-75-54.ap-northeast-1.compute.amazonaws.com:8080/api/v1/clusters/Cluster1]:
{
  "status" : 400,
  "message" : "Specified configuration type is not associated with any service: httpfs-site"
}

```
because `httpfs-site` is not part of default Ambari services' configurartion
