### ISSUE TITLE
The injection of the ambari cluster in the ambari server didn't work

### ISSUE THREAD

**Issue by fotto1** [brooklyncentral/brooklyn-ambari#5]
I tried to get the demo (http://www.cloudsoftcorp.com/blog/2015/04/deploying-an-hadoop-stack-to-a-cloud-using-brooklyn-and-ambari/) running on aws.

The creation of the instances goes successfully but there is no "Cluster1" in the ambari server web interface.

![ambarideployment](https://cloud.githubusercontent.com/assets/12606402/7809346/b84ba244-0399-11e5-88a7-31ccb2687153.png)

![ambariserver](https://cloud.githubusercontent.com/assets/12606402/7809347/b84d5940-0399-11e5-80cb-6f321516039d.png)

I use the apache brooklyn version 0.7.0-SNAPSHOT and the ambari brooklyn version given in the example.

I also try it with the current version of incubator-brooklyn and brooklyn-ambari from git hub today, with the same result.

**Comment by duncangrant** [comment]
@fotto1 Sorry for the slow response.
There's definitely a bug with the blueprint in that it doesn't cope with errors coming from ambari when it tries to deploy the cluster so, as you've seen, it looks like it is up and running even when it has failed.
Having said that if I use the yaml from the blog it works for me. I notice that only one agent has been deployed so I assume you've modified the example yaml.  Could you post the yaml that you used - minus identity and credentials.

regards

Duncan

**Comment by fotto1** [comment]
Hello Duncan,

I use the following blueprint:

```
name: hadoop_deployment
description: Hadoop on Ambari Deployment
location: 
  jclouds:aws-ec2:
    region: eu-west-1
    identity: <aws-identity>
    credential: <aws-credential>
    osFamily: ubuntu
    osVersionRegex: 12.*
    minRam: 8192
services:
- type: io.brooklyn.ambari.AmbariCluster
  brooklyn.config:
    securityGroup: <aws-security-group>
    initialSize: 1
    services:
    - GANGLIA
    - HDFS
    - MAPREDUCE2
    - NAGIOS
    - YARN
    - ZOOKEEPER
```

I also try this with the initialSize 3 but with the same result.

Best Regards,
Felix
